//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Flight"",
            ""id"": ""0879dc72-6edd-453a-82fd-48245f8d4006"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""Value"",
                    ""id"": ""ace422de-3642-4fd1-b80e-e74fd6031d29"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""86c992b2-0ab4-4351-98c0-ef9541a3b9d6"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrottleCut"",
                    ""type"": ""Button"",
                    ""id"": ""73107268-d24c-4d71-b41d-e43719b05884"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrottleFull"",
                    ""type"": ""Button"",
                    ""id"": ""d99893bb-0542-413e-bca3-36a480414858"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMap"",
                    ""type"": ""Button"",
                    ""id"": ""ab4f4dfe-9648-4185-ab00-f4e2f2f1bbe3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""A/D"",
                    ""id"": ""58535909-256b-4d7d-911f-039ecb81a7ab"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4477758a-dc84-4537-b360-efad8bb3cace"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ab38b694-1e24-418a-8f64-9ee4a2a260a5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""e6bd098e-3e82-4628-a6da-65e93a00bd1e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ef24172a-677b-4a9c-aace-f1821598c640"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b6bba48f-b979-4abc-972b-eee6ec5f1986"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Shift/Ctrl"",
                    ""id"": ""e5fe924f-73f9-4647-8201-1c3ee0942b1a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""06fdbc93-fcc5-454a-9681-ccadeffa2397"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0ec2ca0e-c338-428e-b755-401f72cf1d55"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4a7b834a-819b-4bed-bd47-a28a0e4a4737"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""ThrottleCut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6efbc3c2-ef27-4595-bc12-6d595d640ff2"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""ThrottleFull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3de33db1-b964-4fd3-902f-9cadf0038a99"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Warp"",
            ""id"": ""4683bbdc-2d1f-4768-a92d-cf76851c3f07"",
            ""actions"": [
                {
                    ""name"": ""WarpIncrease"",
                    ""type"": ""Button"",
                    ""id"": ""ac70b837-97c3-4a77-926f-ab1127e708ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WarpDecrease"",
                    ""type"": ""Button"",
                    ""id"": ""13603a46-c9f2-4472-97ed-079fdaf23020"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WarpCancel"",
                    ""type"": ""Button"",
                    ""id"": ""d94eace0-84f5-41f4-9bd6-da7bc298b952"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""98d9eacc-94ef-4366-b710-d15ad5b80a9e"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""WarpIncrease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ec2cb62-5e09-43c0-a5a5-be9ad2159441"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""WarpDecrease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b8dcc3-37ee-46de-aa4e-e1d3a77cc820"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""WarpCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard + Mouse"",
            ""bindingGroup"": ""Keyboard + Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Flight
        m_Flight = asset.FindActionMap("Flight", throwIfNotFound: true);
        m_Flight_Steering = m_Flight.FindAction("Steering", throwIfNotFound: true);
        m_Flight_Throttle = m_Flight.FindAction("Throttle", throwIfNotFound: true);
        m_Flight_ThrottleCut = m_Flight.FindAction("ThrottleCut", throwIfNotFound: true);
        m_Flight_ThrottleFull = m_Flight.FindAction("ThrottleFull", throwIfNotFound: true);
        m_Flight_ToggleMap = m_Flight.FindAction("ToggleMap", throwIfNotFound: true);
        // Warp
        m_Warp = asset.FindActionMap("Warp", throwIfNotFound: true);
        m_Warp_WarpIncrease = m_Warp.FindAction("WarpIncrease", throwIfNotFound: true);
        m_Warp_WarpDecrease = m_Warp.FindAction("WarpDecrease", throwIfNotFound: true);
        m_Warp_WarpCancel = m_Warp.FindAction("WarpCancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Flight
    private readonly InputActionMap m_Flight;
    private List<IFlightActions> m_FlightActionsCallbackInterfaces = new List<IFlightActions>();
    private readonly InputAction m_Flight_Steering;
    private readonly InputAction m_Flight_Throttle;
    private readonly InputAction m_Flight_ThrottleCut;
    private readonly InputAction m_Flight_ThrottleFull;
    private readonly InputAction m_Flight_ToggleMap;
    public struct FlightActions
    {
        private @InputActions m_Wrapper;
        public FlightActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_Flight_Steering;
        public InputAction @Throttle => m_Wrapper.m_Flight_Throttle;
        public InputAction @ThrottleCut => m_Wrapper.m_Flight_ThrottleCut;
        public InputAction @ThrottleFull => m_Wrapper.m_Flight_ThrottleFull;
        public InputAction @ToggleMap => m_Wrapper.m_Flight_ToggleMap;
        public InputActionMap Get() { return m_Wrapper.m_Flight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlightActions set) { return set.Get(); }
        public void AddCallbacks(IFlightActions instance)
        {
            if (instance == null || m_Wrapper.m_FlightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlightActionsCallbackInterfaces.Add(instance);
            @Steering.started += instance.OnSteering;
            @Steering.performed += instance.OnSteering;
            @Steering.canceled += instance.OnSteering;
            @Throttle.started += instance.OnThrottle;
            @Throttle.performed += instance.OnThrottle;
            @Throttle.canceled += instance.OnThrottle;
            @ThrottleCut.started += instance.OnThrottleCut;
            @ThrottleCut.performed += instance.OnThrottleCut;
            @ThrottleCut.canceled += instance.OnThrottleCut;
            @ThrottleFull.started += instance.OnThrottleFull;
            @ThrottleFull.performed += instance.OnThrottleFull;
            @ThrottleFull.canceled += instance.OnThrottleFull;
            @ToggleMap.started += instance.OnToggleMap;
            @ToggleMap.performed += instance.OnToggleMap;
            @ToggleMap.canceled += instance.OnToggleMap;
        }

        private void UnregisterCallbacks(IFlightActions instance)
        {
            @Steering.started -= instance.OnSteering;
            @Steering.performed -= instance.OnSteering;
            @Steering.canceled -= instance.OnSteering;
            @Throttle.started -= instance.OnThrottle;
            @Throttle.performed -= instance.OnThrottle;
            @Throttle.canceled -= instance.OnThrottle;
            @ThrottleCut.started -= instance.OnThrottleCut;
            @ThrottleCut.performed -= instance.OnThrottleCut;
            @ThrottleCut.canceled -= instance.OnThrottleCut;
            @ThrottleFull.started -= instance.OnThrottleFull;
            @ThrottleFull.performed -= instance.OnThrottleFull;
            @ThrottleFull.canceled -= instance.OnThrottleFull;
            @ToggleMap.started -= instance.OnToggleMap;
            @ToggleMap.performed -= instance.OnToggleMap;
            @ToggleMap.canceled -= instance.OnToggleMap;
        }

        public void RemoveCallbacks(IFlightActions instance)
        {
            if (m_Wrapper.m_FlightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlightActions instance)
        {
            foreach (var item in m_Wrapper.m_FlightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlightActions @Flight => new FlightActions(this);

    // Warp
    private readonly InputActionMap m_Warp;
    private List<IWarpActions> m_WarpActionsCallbackInterfaces = new List<IWarpActions>();
    private readonly InputAction m_Warp_WarpIncrease;
    private readonly InputAction m_Warp_WarpDecrease;
    private readonly InputAction m_Warp_WarpCancel;
    public struct WarpActions
    {
        private @InputActions m_Wrapper;
        public WarpActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @WarpIncrease => m_Wrapper.m_Warp_WarpIncrease;
        public InputAction @WarpDecrease => m_Wrapper.m_Warp_WarpDecrease;
        public InputAction @WarpCancel => m_Wrapper.m_Warp_WarpCancel;
        public InputActionMap Get() { return m_Wrapper.m_Warp; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WarpActions set) { return set.Get(); }
        public void AddCallbacks(IWarpActions instance)
        {
            if (instance == null || m_Wrapper.m_WarpActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WarpActionsCallbackInterfaces.Add(instance);
            @WarpIncrease.started += instance.OnWarpIncrease;
            @WarpIncrease.performed += instance.OnWarpIncrease;
            @WarpIncrease.canceled += instance.OnWarpIncrease;
            @WarpDecrease.started += instance.OnWarpDecrease;
            @WarpDecrease.performed += instance.OnWarpDecrease;
            @WarpDecrease.canceled += instance.OnWarpDecrease;
            @WarpCancel.started += instance.OnWarpCancel;
            @WarpCancel.performed += instance.OnWarpCancel;
            @WarpCancel.canceled += instance.OnWarpCancel;
        }

        private void UnregisterCallbacks(IWarpActions instance)
        {
            @WarpIncrease.started -= instance.OnWarpIncrease;
            @WarpIncrease.performed -= instance.OnWarpIncrease;
            @WarpIncrease.canceled -= instance.OnWarpIncrease;
            @WarpDecrease.started -= instance.OnWarpDecrease;
            @WarpDecrease.performed -= instance.OnWarpDecrease;
            @WarpDecrease.canceled -= instance.OnWarpDecrease;
            @WarpCancel.started -= instance.OnWarpCancel;
            @WarpCancel.performed -= instance.OnWarpCancel;
            @WarpCancel.canceled -= instance.OnWarpCancel;
        }

        public void RemoveCallbacks(IWarpActions instance)
        {
            if (m_Wrapper.m_WarpActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWarpActions instance)
        {
            foreach (var item in m_Wrapper.m_WarpActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WarpActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WarpActions @Warp => new WarpActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard + Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IFlightActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnThrottle(InputAction.CallbackContext context);
        void OnThrottleCut(InputAction.CallbackContext context);
        void OnThrottleFull(InputAction.CallbackContext context);
        void OnToggleMap(InputAction.CallbackContext context);
    }
    public interface IWarpActions
    {
        void OnWarpIncrease(InputAction.CallbackContext context);
        void OnWarpDecrease(InputAction.CallbackContext context);
        void OnWarpCancel(InputAction.CallbackContext context);
    }
}
